import { Inter } from "next/font/google";
import { Patrick_Hand } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const patrick_hand = Patrick_Hand({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${patrick_hand.className}`}> {children} </body>
    </html>
  );
}
